source 'https://rubygems.org'

gem 'sinatra', '~> 2.0'

gem 'json', '>= 1.8.3'

# Environment
gem 'dotenv', '~> 2.2', '>= 2.2.1'

# Mail
gem 'mail', '~> 2.6', '>= 2.6.6'
gem 'pony', '~> 1.11'
gem 'akismet', '~> 2.0'

group :development do
  gem 'foreman'
end